version: '3.3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "5000:5000"
    environment:
      FLASK_APP: /usr/src/app.py
      FLASK_ENV: development
    command: flask run --host=0.0.0.0 --port=5000 --no-debugger --no-reload
